export const COUNTRIES = [
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'Germany',
  'France',
  'Italy',
  'Spain',
  'Netherlands',
  'Brazil',
  'Mexico',
  'Argentina',
  'Colombia',
  'Egypt',
  'Saudi Arabia',
  'United Arab Emirates',
  'South Africa',
  'Nigeria',
  'Kenya',
  'India',
  'Japan',
  'South Korea',
  'China',
  'Russia',
  'Turkey',
  'Poland',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Switzerland',
  'Austria',
  'Belgium',
  'Portugal',
  'Greece',
  'Ireland',
  'New Zealand',
  'Singapore',
  'Malaysia',
  'Indonesia',
  'Philippines',
  'Thailand',
  'Vietnam',
  'Chile',
  'Peru',
  'Morocco',
  'Algeria',
  'Tunisia',
  'Pakistan',
  'Bangladesh',
  'Ukraine',
  'Romania',
  'Czech Republic',
  'Hungary',
];

export const COUNTRY_FLAGS: Record<string, string> = {
  'United States': '🇺🇸',
  'United Kingdom': '🇬🇧',
  'Canada': '🇨🇦',
  'Australia': '🇦🇺',
  'Germany': '🇩🇪',
  'France': '🇫🇷',
  'Italy': '🇮🇹',
  'Spain': '🇪🇸',
  'Netherlands': '🇳🇱',
  'Brazil': '🇧🇷',
  'Mexico': '🇲🇽',
  'Argentina': '🇦🇷',
  'Colombia': '🇨🇴',
  'Egypt': '🇪🇬',
  'Saudi Arabia': '🇸🇦',
  'United Arab Emirates': '🇦🇪',
  'South Africa': '🇿🇦',
  'Nigeria': '🇳🇬',
  'Kenya': '🇰🇪',
  'India': '🇮🇳',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'China': '🇨🇳',
  'Russia': '🇷🇺',
  'Turkey': '🇹🇷',
  'Poland': '🇵🇱',
  'Sweden': '🇸🇪',
  'Norway': '🇳🇴',
  'Denmark': '🇩🇰',
  'Finland': '🇫🇮',
  'Switzerland': '🇨🇭',
  'Austria': '🇦🇹',
  'Belgium': '🇧🇪',
  'Portugal': '🇵🇹',
  'Greece': '🇬🇷',
  'Ireland': '🇮🇪',
  'New Zealand': '🇳🇿',
  'Singapore': '🇸🇬',
  'Malaysia': '🇲🇾',
  'Indonesia': '🇮🇩',
  'Philippines': '🇵🇭',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Chile': '🇨🇱',
  'Peru': '🇵🇪',
  'Morocco': '🇲🇦',
  'Algeria': '🇩🇿',
  'Tunisia': '🇹🇳',
  'Pakistan': '🇵🇰',
  'Bangladesh': '🇧🇩',
  'Ukraine': '🇺🇦',
  'Romania': '🇷🇴',
  'Czech Republic': '🇨🇿',
  'Hungary': '🇭🇺',
};

export function getCountryFlag(country?: string | null): string {
  if (!country) return '🏴';
  return COUNTRY_FLAGS[country] || '🏴';
}
