export const COUNTRIES = [
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'Germany',
  'France',
  'Italy',
  'Spain',
  'Netherlands',
  'Brazil',
  'Mexico',
  'Argentina',
  'Colombia',
  'Egypt',
  'Saudi Arabia',
  'United Arab Emirates',
  'South Africa',
  'Nigeria',
  'Kenya',
  'India',
  'Japan',
  'South Korea',
  'China',
  'Russia',
  'Turkey',
  'Poland',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Switzerland',
  'Austria',
  'Belgium',
  'Portugal',
  'Greece',
  'Ireland',
  'New Zealand',
  'Singapore',
  'Malaysia',
  'Indonesia',
  'Philippines',
  'Thailand',
  'Vietnam',
  'Chile',
  'Peru',
  'Morocco',
  'Algeria',
  'Tunisia',
  'Pakistan',
  'Bangladesh',
  'Ukraine',
  'Romania',
  'Czech Republic',
  'Hungary',
];

export const COUNTRY_FLAGS: Record<string, string> = {
  'United States': '🇺🇸',
  'United Kingdom': '🇬🇧',
  'Canada': '🇨🇦',
  'Australia': '🇦🇺',
  'Germany': '🇩🇪',
  'France': '🇫🇷',
  'Italy': '🇮🇹',
  'Spain': '🇪🇸',
  'Netherlands': '🇳🇱',
  'Brazil': '🇧🇷',
  'Mexico': '🇲🇽',
  'Argentina': '🇦🇷',
  'Colombia': '🇨🇴',
  'Egypt': '🇪🇬',
  'Saudi Arabia': '🇸🇦',
  'United Arab Emirates': '🇦🇪',
  'South Africa': '🇿🇦',
  'Nigeria': '🇳🇬',
  'Kenya': '🇰🇪',
  'India': '🇮🇳',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'China': '🇨🇳',
  'Russia': '🇷🇺',
  'Turkey': '🇹🇷',
  'Poland': '🇵🇱',
  'Sweden': '🇸🇪',
  'Norway': '🇳🇴',
  'Denmark': '🇩🇰',
  'Finland': '🇫🇮',
  'Switzerland': '🇨🇭',
  'Austria': '🇦🇹',
  'Belgium': '🇧🇪',
  'Portugal': '🇵🇹',
  'Greece': '🇬🇷',
  'Ireland': '🇮🇪',
  'New Zealand': '🇳🇿',
  'Singapore': '🇸🇬',
  'Malaysia': '🇲🇾',
  'Indonesia': '🇮🇩',
  'Philippines': '🇵🇭',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Chile': '🇨🇱',
  'Peru': '🇵🇪',
  'Morocco': '🇲🇦',
  'Algeria': '🇩🇿',
  'Tunisia': '🇹🇳',
  'Pakistan': '🇵🇰',
  'Bangladesh': '🇧🇩',
  'Ukraine': '🇺🇦',
  'Romania': '🇷🇴',
  'Czech Republic': '🇨🇿',
  'Hungary': '🇭🇺',
};

export function getCountryFlag(country?: string | null): string {
  if (!country) return '🏴';
  return COUNTRY_FLAGS[country] || '🏴';
}

/**
 * ISO 3166-1 alpha-2 code ("SA", "EG") for a stored country name, decoded
 * from its flag emoji — each flag is two regional-indicator symbols that
 * spell the code — so there's no second country table to keep in sync.
 * Returns '' for unknown/missing countries.
 */
export function getCountryCode(country?: string | null): string {
  const flag = country ? COUNTRY_FLAGS[country] : undefined;
  if (!flag) return '';
  return Array.from(flag)
    .map(ch => String.fromCharCode((ch.codePointAt(0) ?? 0) - 0x1f1e6 + 65))
    .join('');
}
